#!/usr/bin/env bash
# Switch the dev server back off the production copy and onto your own dev
# database, by removing the .env.local that sync-prod-to-local.sh wrote.
#
# The copy itself (whobela_prod_copy and ./uploads-prod) is left in place, so
# switching back is just another run of sync-prod-to-local.sh — or re-run it to
# refresh the copy from prod.
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_LOCAL="${PROJECT_ROOT}/.env.local"

if [[ ! -f "$ENV_LOCAL" ]]; then
  echo "==> No .env.local — already using the dev database (.env)."
  exit 0
fi

# Only remove the file if this script's counterpart generated it; a hand-written
# .env.local may hold settings that have nothing to do with the prod copy.
if ! grep -q "sync-prod-to-local.sh" "$ENV_LOCAL"; then
  echo "ERROR: .env.local was not generated by sync-prod-to-local.sh." >&2
  echo "       Leaving it alone — remove the DATABASE_URL/UPLOAD_DIR lines yourself." >&2
  exit 1
fi

rm "$ENV_LOCAL"
echo "==> Removed .env.local. Restart \`npm run dev\` to use your dev database."
